[env]
RUSTFLAGS = "-C debuginfo=0 -C target-cpu=native -C opt-level=3 -C codegen-units=1 -C strip=symbols -C panic=abort -C linker=clang -Z panic_abort_tests -C lto=fat -C embed-bitcode=yes -Zdylib-lto -C target-feature=+crt-static"

[build]
target = "x86_64-unknown-linux-gnu"
rustflags = [
    "-C", "debuginfo=0",
    "-C", "target-cpu=native",
    "-C", "opt-level=3",
    "-C", "codegen-units=1",
    "-C", "strip=symbols",
    "-C", "panic=abort",
    "-C", "linker=clang",
    "-Z", "panic_abort_tests",
    "-C", "lto=fat",
    "-C", "embed-bitcode=yes",
    "-Z", "dylib-lto",
    "-C", "target-feature=+crt-static",
]
